/**
 * Real-hardware-derived PCB definitions.
 * All units are millimetres, origin at board centre.
 * `x` runs along the board width, `y` along the board height (mapped to Z in 3D).
 */

export type PartKind =
  | "ic-qfp" // quad flat pack (MCU, SoC)
  | "ic-dip" // through-hole DIP (ATmega328P)
  | "ic-so" // small outline (regulators, drivers, flash)
  | "shield" // RF module can (ESP32-WROOM)
  | "header" // 0.1" pin header
  | "usb-b"
  | "usb-mini"
  | "usb-micro"
  | "usb-c"
  | "usb-a"
  | "rj45"
  | "hdmi"
  | "barrel"
  | "cap-elec" // electrolytic can
  | "cap-smd" // MLCC
  | "res-smd"
  | "led"
  | "crystal"
  | "button"
  | "sdcard"
  | "fpc"; // flat-flex connector

export type Part = {
  id: string;
  kind: PartKind;
  /** centre position, mm */
  x: number;
  y: number;
  /** footprint size, mm */
  w: number;
  h: number;
  /** body height, mm (optional per-kind default) */
  z?: number;
  /** pin count for headers / ICs */
  pins?: number;
  /** rows for headers */
  rows?: number;
  /** rotate 90° in board plane */
  rot?: boolean;
  color?: string;
  label?: string;
  /** description surfaced in the inspector */
  name?: string;
  spec?: string[];
};

export type BoardDef = {
  id: string;
  name: string;
  subtitle: string;
  /** board outline, mm */
  w: number;
  h: number;
  thickness: number;
  /** soldermask colour */
  mask: string;
  silk: string;
  holes: { x: number; y: number; r: number }[];
  parts: Part[];
  /** trace network: index pairs into parts, routed manhattan */
  nets: [number, number][];
};

const hdr = (
  id: string,
  x: number,
  y: number,
  pins: number,
  rows = 1,
  rot = false,
  name?: string,
): Part => ({
  id,
  kind: "header",
  x,
  y,
  w: rot ? 2.54 * rows : pins * 2.54,
  h: rot ? pins * 2.54 : 2.54 * rows,
  pins,
  rows,
  rot,
  name: name ?? `${pins}-pin header`,
  spec: ["Pitch: 2.54 mm", "Plating: gold over nickel"],
});

const passives = (
  prefix: string,
  coords: [number, number][],
  kind: PartKind = "res-smd",
): Part[] =>
  coords.map(([x, y], i) => ({
    id: `${prefix}${i + 1}`,
    kind,
    x,
    y,
    w: kind === "res-smd" ? 1.6 : 2,
    h: kind === "res-smd" ? 0.8 : 1.25,
    name: kind === "res-smd" ? "Chip resistor 0603" : "MLCC capacitor 0805",
  }));

export const arduinoUno: BoardDef = {
  id: "uno",
  name: "Arduino Uno R3",
  subtitle: "ATmega328P · 68.6 × 53.4 mm · 2-layer FR-4",
  w: 68.6,
  h: 53.4,
  thickness: 1.6,
  mask: "#0d5b8c",
  silk: "#e8f1f5",
  holes: [
    { x: -20.5, y: 21, r: 1.6 },
    { x: 25.4, y: 21, r: 1.6 },
    { x: 25.4, y: -19, r: 1.6 },
    { x: -13, y: -21, r: 1.6 },
  ],
  parts: [
    {
      id: "U1",
      kind: "ic-dip",
      x: 4,
      y: -8,
      w: 34,
      h: 10.2,
      z: 4,
      pins: 28,
      label: "ATMEGA328P",
      name: "ATmega328P-PU microcontroller",
      spec: ["Core: 8-bit AVR @ 16 MHz", "Flash: 32 KB", "Package: PDIP-28"],
    },
    {
      id: "U2",
      kind: "ic-so",
      x: -19,
      y: -14,
      w: 10,
      h: 6,
      z: 1.75,
      pins: 32,
      label: "ATMEGA16U2",
      name: "ATmega16U2 USB bridge",
      spec: ["USB 2.0 full-speed", "Package: TQFP-32"],
    },
    {
      id: "J1",
      kind: "usb-b",
      x: -28,
      y: 15,
      w: 12,
      h: 16,
      z: 11,
      name: "USB Type-B receptacle",
      spec: ["Power: 5 V / 500 mA", "Data: USB 2.0"],
    },
    {
      id: "X1",
      kind: "barrel",
      x: -27,
      y: -17,
      w: 14,
      h: 9,
      z: 11,
      name: "DC barrel jack",
      spec: ["Input: 7–12 V DC", "Centre positive, 2.1 mm"],
    },
    hdr("JD", 8, 23.5, 10, 1, false, "Digital 8–13 / GND / AREF header"),
    hdr("JD2", -13, 23.5, 8, 1, false, "Digital 0–7 header"),
    hdr("JP", 10, -23.5, 6, 1, false, "Analog A0–A5 header"),
    hdr("JPW", -12, -23.5, 8, 1, false, "Power header"),
    hdr("ICSP", 30, -3, 3, 2, false, "ICSP programming header"),
    {
      id: "Y1",
      kind: "crystal",
      x: -8,
      y: 6,
      w: 11,
      h: 4.5,
      z: 4.2,
      name: "16 MHz quartz crystal",
      spec: ["Load: 22 pF", "Tolerance: ±30 ppm"],
    },
    {
      id: "U3",
      kind: "ic-so",
      x: -22,
      y: -5,
      w: 6.5,
      h: 6.5,
      z: 2.3,
      pins: 3,
      label: "NCP1117",
      name: "5 V linear regulator",
      spec: ["Dropout: 1.2 V", "Package: SOT-223"],
    },
    {
      id: "C1",
      kind: "cap-elec",
      x: -15,
      y: -13,
      w: 6.3,
      h: 6.3,
      z: 7,
      name: "Electrolytic capacitor",
      spec: ["47 µF / 25 V", "Low ESR"],
    },
    {
      id: "C2",
      kind: "cap-elec",
      x: -6,
      y: -17,
      w: 6.3,
      h: 6.3,
      z: 7,
      name: "Electrolytic capacitor",
      spec: ["47 µF / 25 V", "Low ESR"],
    },
    {
      id: "SW1",
      kind: "button",
      x: -30,
      y: 3,
      w: 6,
      h: 6,
      z: 3.5,
      name: "Reset tact switch",
      spec: ["Travel: 0.25 mm", "Force: 160 gf"],
    },
    {
      id: "L",
      kind: "led",
      x: 2,
      y: 12,
      w: 2,
      h: 1.25,
      color: "#ffcc33",
      name: "LED L (pin 13)",
      spec: ["0805 chip LED", "Amber"],
    },
    {
      id: "ON",
      kind: "led",
      x: 6,
      y: 12,
      w: 2,
      h: 1.25,
      color: "#6ee36e",
      name: "Power LED",
      spec: ["0805 chip LED", "Green"],
    },
    ...passives("R", [
      [0, 16],
      [4, 16],
      [10, 16],
      [-4, 10],
      [16, -18],
      [20, -14],
      [24, 8],
      [12, 2],
      [-2, -20],
      [18, 16],
    ]),
    ...passives(
      "C",
      [
        [-10, -2],
        [8, -2],
        [20, 2],
        [-18, 8],
        [26, -10],
        [14, 8],
      ],
      "cap-smd",
    ),
  ],
  nets: [
    [0, 2],
    [0, 4],
    [0, 5],
    [0, 6],
    [0, 7],
    [0, 8],
    [0, 9],
    [0, 1],
    [1, 2],
    [10, 0],
    [11, 3],
    [12, 3],
    [14, 0],
    [15, 0],
  ],
};

export const esp32Devkit: BoardDef = {
  id: "esp32",
  name: "ESP32 DevKit V1",
  subtitle: "ESP32-WROOM-32 · 51.5 × 28.3 mm · 4-layer",
  w: 51.5,
  h: 28.3,
  thickness: 1.6,
  mask: "#111418",
  silk: "#f2f4f5",
  holes: [],
  parts: [
    {
      id: "M1",
      kind: "shield",
      x: 3,
      y: 0,
      w: 25.5,
      h: 18,
      z: 3.1,
      label: "ESP32-WROOM-32",
      name: "ESP32-WROOM-32 module",
      spec: ["Dual-core Xtensa LX6 @ 240 MHz", "Wi-Fi 802.11 b/g/n + BT 4.2", "4 MB SPI flash"],
    },
    {
      id: "J1",
      kind: "usb-micro",
      x: -23,
      y: 0,
      w: 8,
      h: 5.6,
      z: 2.7,
      name: "Micro-USB receptacle",
      spec: ["USB 2.0 / CP2102 bridge", "5 V input"],
    },
    hdr("JL", 3, 12.5, 15, 1, false, "Left GPIO header"),
    hdr("JR", 3, -12.5, 15, 1, false, "Right GPIO header"),
    {
      id: "U2",
      kind: "ic-so",
      x: -14,
      y: -7,
      w: 5,
      h: 5,
      z: 1.1,
      pins: 28,
      label: "CP2102",
      name: "CP2102N USB-UART bridge",
      spec: ["Up to 3 Mbaud", "Package: QFN-28"],
    },
    {
      id: "U3",
      kind: "ic-so",
      x: -14,
      y: 5,
      w: 3.2,
      h: 3.2,
      z: 1.2,
      pins: 5,
      label: "AMS1117",
      name: "3.3 V LDO regulator",
      spec: ["Output: 3.3 V / 1 A", "Package: SOT-223"],
    },
    {
      id: "SW1",
      kind: "button",
      x: 20,
      y: 6,
      w: 4.5,
      h: 4.5,
      z: 2.2,
      name: "EN reset button",
      spec: ["SMD tact switch"],
    },
    {
      id: "SW2",
      kind: "button",
      x: 20,
      y: -6,
      w: 4.5,
      h: 4.5,
      z: 2.2,
      name: "BOOT strapping button",
      spec: ["Holds GPIO0 low"],
    },
    {
      id: "D1",
      kind: "led",
      x: -6,
      y: -9,
      w: 1.6,
      h: 0.8,
      color: "#6ee36e",
      name: "Power LED",
      spec: ["0603 chip LED"],
    },
    {
      id: "D2",
      kind: "led",
      x: -3,
      y: -9,
      w: 1.6,
      h: 0.8,
      color: "#4aa8ff",
      name: "GPIO2 status LED",
      spec: ["0603 chip LED"],
    },
    ...passives("R", [
      [-18, 3],
      [-18, -3],
      [-10, 7],
      [-10, -7],
      [16, 9],
      [16, -9],
      [12, 9],
    ]),
    ...passives(
      "C",
      [
        [-20, 6],
        [-20, -6],
        [-8, 4],
        [18, 2],
        [18, -2],
      ],
      "cap-smd",
    ),
  ],
  nets: [
    [0, 1],
    [0, 2],
    [0, 3],
    [0, 4],
    [4, 1],
    [0, 5],
    [0, 6],
    [0, 7],
    [5, 0],
    [8, 0],
    [9, 0],
  ],
};

export const arduinoNano: BoardDef = {
  id: "nano",
  name: "Arduino Nano",
  subtitle: "ATmega328P · 45 × 18 mm · 2-layer",
  w: 45,
  h: 18,
  thickness: 1.6,
  mask: "#0e5f4a",
  silk: "#eef5f2",
  holes: [],
  parts: [
    {
      id: "U1",
      kind: "ic-qfp",
      x: 2,
      y: 0,
      w: 7,
      h: 7,
      z: 1.2,
      pins: 32,
      label: "ATMEGA328P",
      name: "ATmega328P-AU microcontroller",
      spec: ["8-bit AVR @ 16 MHz", "Package: TQFP-32"],
    },
    {
      id: "J1",
      kind: "usb-mini",
      x: -19,
      y: 0,
      w: 9,
      h: 7.5,
      z: 4,
      name: "Mini-USB receptacle",
      spec: ["USB 2.0", "FT232 bridge"],
    },
    hdr("JA", 0, 7.6, 15, 1, false, "Header A (D2–D13)"),
    hdr("JB", 0, -7.6, 15, 1, false, "Header B (A0–A7 / power)"),
    {
      id: "U2",
      kind: "ic-so",
      x: -9,
      y: 3,
      w: 5,
      h: 4.4,
      z: 1,
      pins: 16,
      label: "FT232RL",
      name: "FT232RL USB-UART",
      spec: ["Package: SSOP-28"],
    },
    {
      id: "Y1",
      kind: "crystal",
      x: 10,
      y: 3,
      w: 3.2,
      h: 2.5,
      z: 0.9,
      name: "16 MHz resonator",
      spec: ["SMD, ±0.5 %"],
    },
    {
      id: "SW1",
      kind: "button",
      x: 16,
      y: -2,
      w: 3.5,
      h: 3.5,
      z: 2,
      name: "Reset switch",
      spec: ["SMD tact"],
    },
    {
      id: "D1",
      kind: "led",
      x: 8,
      y: -3.5,
      w: 1.6,
      h: 0.8,
      color: "#ffcc33",
      name: "LED L",
      spec: ["0603 chip LED"],
    },
    ...passives("R", [
      [-4, 3],
      [-4, -3],
      [5, -3],
      [12, -3],
      [-13, -2],
    ]),
    ...passives(
      "C",
      [
        [-6, 0],
        [6, 3],
        [14, 2],
      ],
      "cap-smd",
    ),
  ],
  nets: [
    [0, 1],
    [0, 2],
    [0, 3],
    [0, 4],
    [4, 1],
    [0, 5],
    [0, 6],
    [0, 7],
  ],
};

export const raspberryPi: BoardDef = {
  id: "pi",
  name: "Raspberry Pi 4 Model B",
  subtitle: "BCM2711 · 85 × 56 mm · 6-layer",
  w: 85,
  h: 56,
  thickness: 1.4,
  mask: "#0a5a3f",
  silk: "#eaf3ee",
  holes: [
    { x: -38.5, y: 24.5, r: 1.4 },
    { x: 19.5, y: 24.5, r: 1.4 },
    { x: -38.5, y: -24.5, r: 1.4 },
    { x: 19.5, y: -24.5, r: 1.4 },
  ],
  parts: [
    {
      id: "U1",
      kind: "ic-qfp",
      x: -8,
      y: 4,
      w: 15,
      h: 15,
      z: 1.4,
      pins: 0,
      label: "BCM2711",
      name: "Broadcom BCM2711 SoC",
      spec: ["Quad Cortex-A72 @ 1.5 GHz", "Package: FCBGA"],
    },
    {
      id: "U2",
      kind: "ic-so",
      x: -8,
      y: -12,
      w: 12,
      h: 9,
      z: 1.1,
      pins: 96,
      label: "LPDDR4",
      name: "LPDDR4-3200 SDRAM",
      spec: ["Capacity: 4 GB", "Package: FBGA"],
    },
    hdr("J8", -9, 24, 20, 2, false, "40-pin GPIO header"),
    {
      id: "J2",
      kind: "usb-c",
      x: -33,
      y: -25,
      w: 9,
      h: 4,
      z: 3.2,
      rot: false,
      name: "USB-C power input",
      spec: ["5 V / 3 A", "USB PD sink"],
    },
    {
      id: "J3",
      kind: "hdmi",
      x: -18,
      y: -26,
      w: 7.5,
      h: 4,
      z: 3,
      name: "micro-HDMI 0",
      spec: ["4Kp60 output"],
    },
    {
      id: "J4",
      kind: "hdmi",
      x: -5,
      y: -26,
      w: 7.5,
      h: 4,
      z: 3,
      name: "micro-HDMI 1",
      spec: ["4Kp30 output"],
    },
    {
      id: "J5",
      kind: "usb-a",
      x: 36,
      y: 12,
      w: 17,
      h: 15,
      z: 8,
      rot: true,
      name: "USB 3.0 dual port",
      spec: ["5 Gb/s", "Blue insulator"],
    },
    {
      id: "J6",
      kind: "usb-a",
      x: 36,
      y: -6,
      w: 17,
      h: 15,
      z: 8,
      rot: true,
      name: "USB 2.0 dual port",
      spec: ["480 Mb/s"],
    },
    {
      id: "J7",
      kind: "rj45",
      x: 34,
      y: -20,
      w: 16,
      h: 14,
      z: 13.5,
      rot: true,
      name: "Gigabit Ethernet jack",
      spec: ["1000BASE-T", "Integrated magnetics"],
    },
    {
      id: "U4",
      kind: "ic-qfp",
      x: 16,
      y: -14,
      w: 9,
      h: 9,
      z: 1.1,
      pins: 64,
      label: "LAN7515",
      name: "USB 3.0 hub + GbE controller",
      spec: ["Package: QFN"],
    },
    {
      id: "U5",
      kind: "ic-so",
      x: 8,
      y: 12,
      w: 6,
      h: 5,
      z: 1,
      pins: 20,
      label: "PMIC",
      name: "MxL7704 power management",
      spec: ["4 rails", "Package: QFN-24"],
    },
    {
      id: "J9",
      kind: "fpc",
      x: 22,
      y: 16,
      w: 3,
      h: 17,
      z: 2.6,
      name: "CSI-2 camera connector",
      spec: ["15-way, 1 mm pitch"],
    },
    {
      id: "J10",
      kind: "fpc",
      x: -26,
      y: 12,
      w: 3,
      h: 17,
      z: 2.6,
      name: "DSI display connector",
      spec: ["15-way, 1 mm pitch"],
    },
    {
      id: "J11",
      kind: "sdcard",
      x: -40,
      y: 0,
      w: 13,
      h: 14,
      z: 1.6,
      rot: false,
      name: "microSD card slot",
      spec: ["Push-pull, SDR50"],
    },
    {
      id: "D1",
      kind: "led",
      x: -40,
      y: 21,
      w: 1.6,
      h: 0.8,
      color: "#6ee36e",
      name: "Power LED",
      spec: ["0603 chip LED"],
    },
    {
      id: "D2",
      kind: "led",
      x: -40,
      y: 18,
      w: 1.6,
      h: 0.8,
      color: "#ff5a5a",
      name: "Activity LED",
      spec: ["0603 chip LED"],
    },
    ...passives("R", [
      [2, 20],
      [6, 20],
      [-20, -18],
      [-14, -18],
      [10, -20],
      [26, 4],
      [30, 20],
      [-30, 4],
      [-30, -8],
      [4, -4],
      [-16, 18],
      [12, 6],
    ]),
    ...passives(
      "C",
      [
        [-2, 14],
        [2, 8],
        [-16, -4],
        [0, -20],
        [20, -6],
        [-24, -14],
        [24, 10],
        [-34, 12],
      ],
      "cap-smd",
    ),
  ],
  nets: [
    [0, 1],
    [0, 2],
    [0, 4],
    [0, 5],
    [0, 9],
    [9, 6],
    [9, 7],
    [9, 8],
    [0, 10],
    [0, 11],
    [0, 12],
    [0, 13],
    [10, 3],
    [0, 14],
    [0, 15],
  ],
};

export const boards: BoardDef[] = [arduinoUno, esp32Devkit, arduinoNano, raspberryPi];

export const boardById = (id: string) => boards.find((b) => b.id === id) ?? arduinoUno;
